Print a better error message when a test runner exits unexpectedly (#182)
* Print a better error message when a test runner exits unexpectedly

Here's what this looks like when the dogfood version panics during a
test:

```
<internal test runner error>: ERRORED
--- <internal test runner error>: ERRORED ---
-- Unexpected Test Runner Failure --

The test command

    target/debug/abq_cargo --all-features

exited unexpectedly with code `101` before completing all abq test requests.

The command had no standard stdout.

Here's the standard stderr of the command:
    thread 'main' panicked at 'explicit panic', crates/abq_runners/cargo/src/bin.rs:99:21
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(completed in 27 ms)
<internal test runner error>: ERRORED
--- <internal test runner error>: ERRORED ---
-- Unexpected Test Runner Failure --

The test command

    target/debug/abq_cargo --all-features

exited unexpectedly with code `101` before completing all abq test requests.

The command had no standard stdout.

Here's the standard stderr of the command:
    thread 'main' panicked at 'explicit panic', crates/abq_runners/cargo/src/bin.rs:99:21
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(completed in 27 ms)
^Cmake: *** [dogfood] Interrupt: 2
```

As mentioned in #172 this should never happen when a native runner is
mature, but it'll be helpful for our debugging while we get there.

This patch doesn't implement draining the test run from the queue when
an error like this happens, because there are some additional edge cases
there I'd like to think through before we do that, and I don't think
drainage in these cases is too important for us right now.

Closes #172

* Address lints